### ISSUE TITLE
Locale Identifier

### ISSUE THREAD

**Issue by LazyMink** [imvalient/geocode#13]
The issue is, I'm receiving coordinates from a completely different country.
is there a way to specify the locale identifier? 

geoCode.forwardGeocoding(address: street, locale: "nl_NL")

or 

geoCode.reverseGeocoding(latitude: latitude, longitude: longitude, locale: "nl_NL");

Thanks in advance for any help

**Comment by imvalient** [comment]
Hello Cressed,

Could you send me the request that gives you the wrong coordinates? and the expected coordinates.

Thanks
