### ISSUE TITLE
forwardGeocoding does not work from iOS app

### ISSUE THREAD

**Issue by dancout** [imvalient/geocode#19]
### Description
- I have created a flutter app and recents the `forwardGeocoding` function has stopped working as I would expect.
    - The body of the response received seems to be `error code: 1020`
    - I found this by setting a breakpoint on line 66 of `geocode_client.dart`
- To verify, I am using the exact line of code specified in the pub.dev example, `var response = await GeoCode().forwardGeocoding(address: locality);`
- I am not passing in any auth key, as I planned to use the free tier
- I've found through my own research that running the following GET request *does work* from the browser, but it *does not work* when running from a mobile application. I'm not sure if that's pertinent here.
    - https://geocode.xyz/Chicago?geoit=json
    
### Misc
- I'm not sure if this issue belongs in this repo, or with the actual owners of geocode.xyz

**Comment by imvalient** [comment]
A new release has been published that fixes this bug
