### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by vipinnegi90** [imvalient/geocode#3]
Hi, I was trying your library and ran into this error. I am not able to extract the data from reverseGeocoding if I try like this: 

```
try{
      Address newAddress = await GeoCode().reverseGeocoding(latitude: latitude, longitude: longitude);
      print(newAddress.city);
    } catch (e) {
      print(e);
    }
```

Error : type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

**Comment by imvalient** [comment]
Hello @vipinnegi90,

What's the type and value of both `latitude` and `longitude` variables?

*I've removed your API key from the original post, don't share it, keep it for yourself.

**Comment by imvalient** [comment]
I've been reviewing some specífic geocode requests and found out it could return an empty object for some of the attributes, which mainly caused the error you're reporting. I've worked on a fix that's already published.

Upgrade the package dependency, and it should be fixed.

```YAML
dependencies:
  geocode: ^0.1.3
```

**Comment by vipinnegi90** [comment]
@imvalient thanks for removing my key from op. Is there a way to delete the key and create a new one on my existing account as the key exposed for a while.

I updated the dependencies and now it shows a different error : 
> Invalid argument(s): The source must not be null

after few tries I was getting: 
> [Error]: (006) Request Throttled. Over Rate limit: up to 2 per sec. See geocode.xyz/pricing

and I'm not passing any key, since requests are throttled @ 1req/second for free requests.
Is there something that I'm missing?

**Comment by imvalient** [comment]
Could you send me the values of latitude & longitude you're calling the function with?

Does it happen with all the calls you're making?

To change the API Key you should create a new account, if you wanna keep the account, write to geocode.xyz support team.

https://geocode.xyz/contact

**Comment by vipinnegi90** [comment]
Thanks for the contact info, I'll surely contact the support. 

I was trying to pass : 13.023254762760828, 77.64545207539284
[Geocode](https://pub.dev/packages/geocoder) lib is fetching the location name for me. I was having issues with android since android fetches the short decimals for my marker eg. 13.023254, 77.645452 and geocoder resolves it in not proper way. With iOS I didn't face such issues as I get very specific location with higher decimal points like above.
