### ISSUE TITLE
fordwardGeocoding is returning the wrong coordinates

### ISSUE THREAD

**Issue by permadart** [imvalient/geocode#8]
`var coordinates = await geoCode.forwardGeocoding(address: prediction.description);`

This line is returning 20.6847, -103.2189

The correct coordinates are 20.686010, -103.423210

This is an example but most of the addresses I'm trying return the wrong coordinates. What am I doing wrong? This used to work fine.

**Comment by imvalient** [comment]
Hello Esteban,

Could you provide me with the real value of the variable "prediction.description" that returns you those coordinates?

Thanks
