### ISSUE TITLE
Request Throttled Issue

### ISSUE THREAD

**Issue by iamjithinjohnson** [imvalient/geocode#9]
``` GeoCode(apiKey: kGoogleApiKey) ```
I added google map apikey but it shows
```
Unhandled Exception: [Error]: (006) Request Throttled. Over Rate limit: up to 2 per sec. See geocode.xyz/pricing
```

please help

**Comment by imvalient** [comment]
Hello Jithin,

It does not work with Google Maps API. Check this page to retrieve more information about the supported API and its Keys.
http://geocode.xyz/pricing

**Comment by iamjithinjohnson** [comment]
ok. Thank you for your quick response
